package com.ssafy.edu.jwt.model;

public class Token {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column token.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column token.access_token
	 * @mbg.generated
	 */
	private String accessToken;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column token.is_logged_out
	 * @mbg.generated
	 */
	private Boolean isLoggedOut;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column token.refresh_token
	 * @mbg.generated
	 */
	private String refreshToken;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column token.user_id
	 * @mbg.generated
	 */
	private Integer userId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column token.id
	 * @return  the value of token.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column token.id
	 * @param id  the value for token.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column token.access_token
	 * @return  the value of token.access_token
	 * @mbg.generated
	 */
	public String getAccessToken() {
		return accessToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column token.access_token
	 * @param accessToken  the value for token.access_token
	 * @mbg.generated
	 */
	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken == null ? null : accessToken.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column token.is_logged_out
	 * @return  the value of token.is_logged_out
	 * @mbg.generated
	 */
	public Boolean getIsLoggedOut() {
		return isLoggedOut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column token.is_logged_out
	 * @param isLoggedOut  the value for token.is_logged_out
	 * @mbg.generated
	 */
	public void setIsLoggedOut(Boolean isLoggedOut) {
		this.isLoggedOut = isLoggedOut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column token.refresh_token
	 * @return  the value of token.refresh_token
	 * @mbg.generated
	 */
	public String getRefreshToken() {
		return refreshToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column token.refresh_token
	 * @param refreshToken  the value for token.refresh_token
	 * @mbg.generated
	 */
	public void setRefreshToken(String refreshToken) {
		this.refreshToken = refreshToken == null ? null : refreshToken.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column token.user_id
	 * @return  the value of token.user_id
	 * @mbg.generated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column token.user_id
	 * @param userId  the value for token.user_id
	 * @mbg.generated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table token
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", accessToken=").append(accessToken);
		sb.append(", isLoggedOut=").append(isLoggedOut);
		sb.append(", refreshToken=").append(refreshToken);
		sb.append(", userId=").append(userId);
		sb.append("]");
		return sb.toString();
	}
}