package com.ssafy.edu.board.model.mapper;

import com.ssafy.edu.board.model.Board;
import com.ssafy.edu.board.model.BoardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BoardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_jwt..boards
     *
     * @mbg.generated
     */
    long countByExample(BoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_jwt..boards
     *
     * @mbg.generated
     */
    int deleteByExample(BoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_jwt..boards
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer boardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_jwt..boards
     *
     * @mbg.generated
     */
    int insert(Board row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_jwt..boards
     *
     * @mbg.generated
     */
    int insertSelective(Board row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_jwt..boards
     *
     * @mbg.generated
     */
    List<Board> selectByExampleWithRowbounds(BoardExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_jwt..boards
     *
     * @mbg.generated
     */
    List<Board> selectByExample(BoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_jwt..boards
     *
     * @mbg.generated
     */
    Board selectByPrimaryKey(Integer boardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_jwt..boards
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Board row, @Param("example") BoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_jwt..boards
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Board row, @Param("example") BoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_jwt..boards
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Board row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_jwt..boards
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Board row);
}